name: OtherAnimalTeleport
main: com.coollord22.otheranimalteleport.OtherAnimalTeleport
version: ${project.version}-b${buildNumber}
author: CoolLord22
load: POSTWORLD
api-version: 1.13
softdepend: [WorldGuard]
commands:
    oat:
        description: A simple plugin to teleport animals!
        aliases: [otheranimalteleport, animalteleport, at, animaltp]
        usage: |
            §7
            §aOtherAnimalTeleport §7(allow users to teleport animals!) 
            §7Version: ${project.version}b-${buildNumber}
            §7

permissions:
    otheranimalteleport.*:
        description: Gives access to all permissions
        children:
            otheranimalteleport.player.*: true
            otheranimalteleport.admin.*: true
    otheranimalteleport.player.*:
        description: Gives access to all regular player permissions
        children:
            otheranimalteleport.player.help: true
            otheranimalteleport.player.use: true
            otheranimalteleport.player.teleportpets: true
            otheranimalteleport.player.teleportleashed: true
    otheranimalteleport.admin.*:
        description: Gives access to all admin permissions
        children:
            otheranimalteleport.admin.updates: true
            otheranimalteleport.admin.reloadconfig: true
    otheranimalteleport.player.help:
        description: Gives access to the help command
        default: true
    otheranimalteleport.player.use: 
        description: Gives access to teleporting animals
        default: true
    otheranimalteleport.player.teleportpets: 
        description: Gives access to teleporting pets (requires otheranimalteleport.player.use)
        default: true
    otheranimalteleport.player.teleportleashed: 
        description: Gives access to teleporting leashed entities (requires otheranimalteleport.player.use)
        default: true
    otheranimalteleport.admin.reloadconfig:
        description: Gives access to reloading config
        default: op
    otheranimalteleport.admin.updates: 
        description: Gives access to update notifications
        default: op