name: OtherAnimalTeleport
main: com.coollord22.otheranimalteleport.OtherAnimalTeleport
version: ${project.version}b-${buildNumber}
author: CoolLord22
api-version: 1.15
commands:
    oat:
        description: A simple plugin to teleport animals!
        usage: |
            §7
            §aOtherAnimalTeleport §7(allow users to teleport animals!) 
            §7Version: 1.3
            §7